# Generated by Django 4.2 on 2023-08-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acadamics_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadamics_id', models.CharField(max_length=100)),
                ('acadamics_title', models.CharField(max_length=100)),
                ('acadamics_subtitle', models.CharField(max_length=100)),
                ('acadamics_duration', models.CharField(max_length=100)),
                ('acadamics_id_1', models.CharField(max_length=100)),
                ('acadamics_title_1', models.CharField(max_length=100)),
                ('acadamics_subtitle_1', models.CharField(max_length=100)),
                ('acadamics_duration_1', models.CharField(max_length=100)),
                ('acadamics_id_2', models.CharField(max_length=100)),
                ('acadamics_title_2', models.CharField(max_length=100)),
                ('acadamics_subtitle_2', models.CharField(max_length=100)),
                ('acadamics_duration_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('message', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Contact Table',
            },
        ),
        migrations.CreateModel(
            name='course_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title_1', models.CharField(max_length=100)),
                ('course_image_1', models.ImageField(upload_to='media')),
                ('course_subtitle_1', models.CharField(max_length=100)),
                ('course_duration_1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_name', models.CharField(max_length=100)),
                ('created_by_link', models.CharField(max_length=100)),
                ('created_by_terms', models.CharField(max_length=100)),
                ('created_by_terms_link', models.CharField(max_length=100)),
                ('created_b_year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='get_touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=150)),
                ('get_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hero_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('main_subtitle_1', models.CharField(max_length=100)),
                ('main_subtitle_2', models.CharField(max_length=100)),
                ('main_subtitle_3', models.CharField(max_length=100)),
                ('main_img', models.ImageField(upload_to='media')),
                ('about_img', models.ImageField(upload_to='media')),
                ('about_title', models.CharField(max_length=100)),
                ('about_subtitle_1', models.CharField(max_length=100)),
                ('about_subtitle_2', models.CharField(max_length=100)),
                ('about_subtitle_3', models.CharField(max_length=100)),
                ('about_text', models.TextField()),
                ('resume_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_image', models.ImageField(upload_to='media')),
                ('project_subtitle', models.CharField(max_length=100)),
                ('project_duration', models.CharField(max_length=300)),
                ('project_link', models.CharField(max_length=200)),
                ('is_key_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='skill_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=100)),
                ('skill_description', models.TextField()),
                ('skill_link', models.CharField(max_length=200)),
                ('skill_section_image', models.ImageField(upload_to='media')),
                ('skill_section_title', models.CharField(max_length=100)),
            ],
        ),
    ]
