# Generated by Django 4.2 on 2023-08-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill_icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_section_image', models.ImageField(upload_to='media')),
                ('skill_section_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill_section',
            name='skill_section_image',
        ),
        migrations.RemoveField(
            model_name='skill_section',
            name='skill_section_title',
        ),
    ]
